### ISSUE TITLE
Things this application needs to do

### ISSUE THREAD

**Issue by Anbranin** [umts/chronos#1]
When this functionality (plus the relevant models needed) is in place, the app should be ready to roll out.
- [ ] Punch in/out with a 7 minute threshhold
- [ ] Request time off
- [ ] View timesheet
- [ ] Approve timesheet
- [ ] View time off requests (calendar)
- [ ] Add/Edit/Delete/Search time punches
- [ ] Hours tracking with automated lunch break after 6 straight hours
- [ ] Shift total rounds to the nearest 15 minutes

**Comment by werebus** [comment]
Can I recommend a [Project](https://github.com/umts/chronos/projects) or [Milestone](https://github.com/umts/chronos/milestones)

**Comment by Anbranin** [comment]
No

**Comment by Anbranin** [comment]
closed because I opened individual issues and made a project
