### ISSUE TITLE
Shift total rounds to the nearest 15 minutes

### ISSUE THREAD

**Issue by Anbranin** [umts/chronos#2]
7 minute threshold.
example:
punch at 8:53 - round up to 9
punch at 8:52 - round down to 8:45

**Comment by werebus** [comment]
Your example and your issue description don't match. Do you round the **total** or the punch-in and punch-out times (I would assume that it was the total).

**Comment by dfaulken** [comment]
This is an interesting question. If I work 8:52-11:08, say, how should that be rounded?

**Comment by werebus** [comment]
Exactly. Here at Transit, that gets you 3.25 hours.

**Comment by nawilliams** [comment]
Actual example:
punch at 8:53 - punch out at 10:31 - Round up to 1.75hr
punch at 8:55 - punch out at 10:31 - Round down to 1.5hr
